<?php
if (! defined('ABSPATH')) {
    exit;
}
echo '<?xml version="1.0" encoding="UTF-8"?>';
?>
<xsl:stylesheet version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
    xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
    xmlns:news="http://www.google.com/schemas/sitemap-news/0.9"
    xmlns:video="http://www.google.com/schemas/sitemap-video/1.1"
    exclude-result-prefixes="sitemap image news video">

<xsl:output method="html" encoding="UTF-8" indent="yes"/>

<xsl:template match="/">
<html lang="en">
<head>
    <title>XML Sitemap — Celestial Sitemap</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: #f0f2f5; color: #1a1a2e; padding: 24px; }
        .container { max-width: 1100px; margin: 0 auto; }
        h1 { font-size: 1.5rem; margin-bottom: 4px; color: #16213e; }
        .subtitle { color: #666; margin-bottom: 24px; font-size: 0.9rem; }
        table { width: 100%; border-collapse: collapse; background: #fff; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,.12); }
        th { background: #16213e; color: #fff; padding: 12px 16px; text-align: left; font-size: 0.85rem; text-transform: uppercase; letter-spacing: 0.05em; }
        td { padding: 10px 16px; border-bottom: 1px solid #eee; font-size: 0.9rem; }
        tr:hover td { background: #f7f8fc; }
        a { color: #0f3460; text-decoration: none; }
        a:hover { text-decoration: underline; }
        .count { background: #e0e7ff; color: #3b5bdb; padding: 2px 10px; border-radius: 12px; font-size: 0.8rem; font-weight: 600; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.75rem; margin-left: 6px; }
        .badge-img { background: #d4edda; color: #155724; }
        .badge-news { background: #cce5ff; color: #004085; }
        .badge-video { background: #fff3cd; color: #856404; }
    </style>
</head>
<body>
<div class="container">
    <h1>XML Sitemap</h1>
    <p class="subtitle">Generated by Celestial Sitemap v<?php echo esc_html(CEL_VERSION); ?></p>

    <xsl:choose>
        <!-- Sitemap Index -->
        <xsl:when test="sitemap:sitemapindex">
            <table>
                <tr>
                    <th>#</th>
                    <th>Sitemap</th>
                    <th>Last Modified</th>
                </tr>
                <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
                    <tr>
                        <td><xsl:value-of select="position()"/></td>
                        <td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
                        <td><xsl:value-of select="sitemap:lastmod"/></td>
                    </tr>
                </xsl:for-each>
            </table>
        </xsl:when>
        <!-- URL Set -->
        <xsl:otherwise>
            <p class="subtitle">
                <span class="count"><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs</span>
            </p>
            <table>
                <tr>
                    <th>#</th>
                    <th>URL</th>
                    <th>Info</th>
                    <th>Last Modified / Published</th>
                </tr>
                <xsl:for-each select="sitemap:urlset/sitemap:url">
                    <tr>
                        <td><xsl:value-of select="position()"/></td>
                        <td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
                        <td>
                            <xsl:if test="count(image:image) &gt; 0">
                                <span class="badge badge-img"><xsl:value-of select="count(image:image)"/> img</span>
                            </xsl:if>
                            <xsl:if test="news:news">
                                <span class="badge badge-news">News</span>
                            </xsl:if>
                            <xsl:if test="count(video:video) &gt; 0">
                                <span class="badge badge-video"><xsl:value-of select="count(video:video)"/> video</span>
                            </xsl:if>
                        </td>
                        <td>
                            <xsl:choose>
                                <xsl:when test="news:news/news:publication_date">
                                    <xsl:value-of select="news:news/news:publication_date"/>
                                </xsl:when>
                                <xsl:otherwise>
                                    <xsl:value-of select="sitemap:lastmod"/>
                                </xsl:otherwise>
                            </xsl:choose>
                        </td>
                    </tr>
                </xsl:for-each>
            </table>
        </xsl:otherwise>
    </xsl:choose>
</div>
</body>
</html>
</xsl:template>
</xsl:stylesheet>
